/**
 * Fixture validation tests
 *
 * This file validates that test fixtures are correctly generated.
 * Without these checks, other tests may fail with confusing errors when fixtures
 * are missing, corrupted, or regenerated with different parameters.
 *
 * Video segments are generated using ffmpeg with solid color frames:
 *   ffmpeg -f lavfi -i "color=c=<color>:s=320x240:r=24:d=10" -f mpegts -codec:v mpeg2video -b:v 500k segments/segment_<index>_<color>.ts
 *
 * - segment_000_red.ts   (0-10s, red solid color)
 * - segment_001_blue.ts  (10-20s, blue solid color)
 * - segment_002_green.ts (20-30s, green solid color)
 *
 * Run these tests after regenerating fixtures to ensure they're valid before
 * running the actual parser/downloader tests.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const fixturesDir = join(__dirname, 'fixtures');

describe('fixtures', () => {
  describe('TS segment files', () => {
    it('should have red segment file (0-10s)', () => {
      const segmentPath = join(fixturesDir, 'segments', 'segment_000_red.ts');
      const buffer = readFileSync(segmentPath);

      expect(buffer.length).toBeGreaterThan(0);
      expect(buffer.length).toBe(105280); // ~103KB as generated by ffmpeg
    });

    it('should have blue segment file (10-20s)', () => {
      const segmentPath = join(fixturesDir, 'segments', 'segment_001_blue.ts');
      const buffer = readFileSync(segmentPath);

      expect(buffer.length).toBeGreaterThan(0);
      expect(buffer.length).toBe(105280);
    });

    it('should have green segment file (20-30s)', () => {
      const segmentPath = join(fixturesDir, 'segments', 'segment_002_green.ts');
      const buffer = readFileSync(segmentPath);

      expect(buffer.length).toBeGreaterThan(0);
      expect(buffer.length).toBe(105280);
    });

    it('should have valid MPEG-TS sync bytes (0x47)', () => {
      const colors = ['red', 'blue', 'green'];
      const indices = ['000', '001', '002'];

      for (let i = 0; i < 3; i++) {
        const segmentPath = join(fixturesDir, 'segments', `segment_${indices[i]}_${colors[i]}.ts`);
        const buffer = readFileSync(segmentPath);

        // MPEG-TS packets start with sync byte 0x47 (71)
        expect(buffer[0]).toBe(0x47);

        // MPEG-TS packets are 188 bytes, check next packet
        if (buffer.length > 188) {
          expect(buffer[188]).toBe(0x47);
        }
      }
    });

    it('should have all segment files of equal size', () => {
      const red = readFileSync(join(fixturesDir, 'segments', 'segment_000_red.ts'));
      const blue = readFileSync(join(fixturesDir, 'segments', 'segment_001_blue.ts'));
      const green = readFileSync(join(fixturesDir, 'segments', 'segment_002_green.ts'));

      expect(red.length).toBe(blue.length);
      expect(blue.length).toBe(green.length);
    });
  });

  describe('M3U8 playlist files', () => {
    it('should have media playlist referencing all segments', () => {
      const content = readFileSync(join(fixturesDir, 'playlist.m3u8'), 'utf-8');

      expect(content).toContain('#EXTM3U');
      expect(content).toContain('segment_000_red.ts');
      expect(content).toContain('segment_001_blue.ts');
      expect(content).toContain('segment_002_green.ts');
      expect(content).toContain('#EXT-X-ENDLIST');
    });

    it('should have master playlist with variants', () => {
      const content = readFileSync(join(fixturesDir, 'master.m3u8'), 'utf-8');

      expect(content).toContain('#EXTM3U');
      expect(content).toContain('#EXT-X-STREAM-INF');
      expect(content).toContain('playlist_480.m3u8');
      expect(content).toContain('playlist_720.m3u8');
      expect(content).toContain('playlist_1080.m3u8');
    });

    it('should have variant playlists for each resolution', () => {
      const variants = ['480', '720', '1080'];

      for (const variant of variants) {
        const content = readFileSync(join(fixturesDir, `playlist_${variant}.m3u8`), 'utf-8');

        expect(content).toContain('#EXTM3U');
        expect(content).toContain('#EXT-X-TARGETDURATION:10');
        expect(content).toContain('#EXT-X-ENDLIST');
      }
    });
  });
});
